name: Check run

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-run:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - run: sudo apt-get update && sudo apt-get install -y nginx && sudo systemctl start nginx

    - name: ZAP Scan
      uses: ./
      id: action-full-scan
      with:
        target: 'http://testfire.net/'
        allow_issue_writing: false